### ISSUE TITLE
passport-steam Guide will be appreciated

### ISSUE THREAD

**Issue by angelhdzmultimedia** [nestjs/passport#1039]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I've tried many solutions and I don't get passport-steam to make the login, but oddly it makes the redirect to the returnURL (in my case http://localhost:5000/api/auth/steam/return).

I'm using PassportStrategy and passing the Strategy from passport-steam as argument, and a "steam" name as second argument.

In the constructor I'm calling super and passing the options I would normally pass to the Steam Strategy when creating a pure Node + Express project.

Then I use the SteamAuthGuard that extends AuthGuard('steam').

### Describe the solution you'd like

It would be nice to include passport-steam in the guides, or even better, a more clear guide on how to add custom strategies.

### What is the motivation / use case for changing the behavior?

?

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
