### ISSUE TITLE
Validate AuthGuard with parameters

### ISSUE THREAD

**Issue by desarrollokrama** [nestjs/passport#12]
## I'm submitting a...
<pre><code>
[ ] Regression
[ ] Bug report
[ ] Feature request
[X] Documentation issue or request
[ ] Support request
</code></pre>

## Minimal reproduction of the problem with instructions
I am using AuthGuard, in the Docs you say that you can call it like this @UseGuards(AuthGuard('jwt')) and the that AuthGuard accepts a second argument, options object that you are able to pass in order to determine the passport behavior.

The idea behind this is that I can make a call like this @UseGuards(AuthGuard('jwt',{roles: 'admin'})) so that I can give access only if the jwt has the 'admin' role. However, it is impossible to access these options from the validate method in the JwtStrategy.

This is my code, extracted from the 19-auth project:

jwt.strategy.ts

<pre><code>
export class JwtStrategy extends PassportStrategy(Strategy) {
    constructor(private readonly authService: AuthService) {
        super({
            jwtFromRequest: ExtractJwt.fromAuthHeaderAsBearerToken(),
            secretOrKey: 'secretKey',
        });
    }

    async validate(payload: JwtPayload, done: Function) {
        const user = await this.authService.validateUser(payload);
        // I want to use the options here in order to check the roles
        if (!user) {
            return done(new UnauthorizedException(), false);
        }
        done(null, user);
    }
}
</code></pre>

auth.controller.ts

<pre><code>
@Get('data')
  @UseGuards(AuthGuard('jwt',{roles: 'admin'}))
  findAll() {
    return 'ACK';
  }
</pre></code>

How can I get these options from there?
Thank you in advance.

**Comment by kamilmysliwiec** [comment]
Use `Reflector` + decorator to provide necessary metadata, more here: https://docs.nestjs.com/guards
To extend `AuthGuard` with your custom logic, see here https://docs.nestjs.com/techniques/authentication **Inheritance**

**Comment by 18anandn** [comment]
You can declare a class within a custom decorator function like this

```
export function RoleGuard(allowedRoles?: string[]) {
  class RolesGuard implements CanActivate {
    canActivate(
      context: ExecutionContext,
    ): boolean | Promise<boolean> | Observable<boolean> {
      const request = context.switchToHttp().getRequest();

      const { currentUser } = request.raw;
      if (
        currentUser &&
        (!allowedRoles || allowedRoles.includes(currentUser.role))
      ) {
        return true;
      }

      return false;
    }
  }

  return UseGuards(RolesGuard);
}
```
