### ISSUE TITLE
How to validate post body first?

### ISSUE THREAD

**Issue by wxs77577** [nestjs/passport#129]
It seems the validation of post body runs **after** auth guards, so I can't validate if some fields valid, how could I validate post body first?

```ts
export class LoginDto {
  @ApiModelProperty({})
  @IsNotEmpty()
  mobile: string

  @ApiModelProperty()
  @IsNotEmpty(})
  password: string
}

//....
@Post('login')
  @ApiOperation({ title: 'Login' })
  @UseGuards(AuthGuard('local'))
  async login(@Body() dto: LoginDto, @Req() req) {
    const user = req.user
    return {
      token: this.jwtService.sign(String(user._id)),
    };
  }
```

**Comment by kamilmysliwiec** [comment]
Pipes are being evaluated after guards. You can move validation logic to either guard or middleware instead and run it manually.

**Comment by rsegecin** [comment]
Conceptually I get that Guards should run before anything else when consuming an endpoint but it would be nice to have it running Validators beforehand instead. I currently have a case that I'm manually having to check if the e-mail address is valid before looking through the database with a malformatted value.

**Comment by kamilmysliwiec** [comment]
This has been discussed many times in the past and we don't plan any change here.
