### ISSUE TITLE
Make the custom callback function part of the service strategy

### ISSUE THREAD

**Issue by bilel-noomene** [nestjs/passport#13]
## I'm submitting a...
<pre><code>
[ ] Regression 
[ ] Bug report
[X] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
If we want to override the strategy callback function, we must provide the custom function each time we use AuthGuard.
<pre><code>
@UseGuards(AuthGuard('jwt', { callback: customCallback }))
</code></pre>

## Expected behavior
It would be more elegant to set the callback function once in the strategy class.
<pre><code>
export declare abstract class AbstractStrategy {
     callback: (err, user, info) => {
        if (err || !user) {
          throw err || new UnauthorizedException();
        }
        return user;
     }
    abstract validate(...args: any[]): any;
}
</code></pre>

## What is the motivation / use case for changing the behavior?
Normally, we use the same function for the entire application.

**Comment by kamilmysliwiec** [comment]
Done.
See https://docs.nestjs.com/techniques/authentication (**Inheritance**) for more details
