### ISSUE TITLE
Allow empty token?

### ISSUE THREAD

**Issue by wxs77577** [nestjs/passport#130]
I have a `/products` api for product list, it can be accessed for guests and logged-in users.
So I need something like a `Jwt Guard` but do not force limit this api must provide a jwt token.
If I use `@UseGuards(AuthGuard('jwt'))` , the guests cannot access it, but if I remove this guard, how could I access `req.user` so that I could return discount price for some users?

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
