### ISSUE TITLE
using @Inject(REQUEST) req breaks passport.

### ISSUE THREAD

**Issue by adonisv79** [nestjs/passport#1561]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

So I have an existing NestJS Authentication API and decided to work with passport tried following this guide https://docs.nestjs.com/recipes/passport

upon completing the Login route (https://docs.nestjs.com/recipes/passport#login-route), I tried to log and instead got this.
```
[Nest] 26216  - 01/27/2024, 4:41:00 PM   ERROR [ExceptionsHandler] Unknown authentication strategy "local"
```

I looked all over and all leads to senseless discussion and samples where the guide works flawlessly for most. But I reached on discussion in stackoverflow which gave some ideas. https://stackoverflow.com/questions/69788605/nestjs-error-unknown-authentication-strategy-local/72433994#72433994

so it turns out once I use passport in nestjs we have to scrap using it and find complex ways on getting things from the request, ugh!

### Minimum reproduction code

https://github.com/adonisv79/akosi/tree/master/akosi-api

### Steps to reproduce

1. follow the guide up to https://docs.nestjs.com/recipes/passport#login-route
2. try to login, it should work
3. go to the AuthService class and add in the constroctor the following
```
@Inject(REQUEST) private readonly req: Request
```
4. login again. it will now claim there is no such strategy.

### Expected behavior

Its either of these:
1. It should not misdirect and just say the issue is your providers are not allowed to use @Inject(REQUEST). This way we know that we do not need to use passport as its not built to work well with nestjs
2, It should allow to use @Inject(REQUEST) together with passport.

### Package version

10.0.3

### Passport version

0.7.0

### NestJS version

10.2.1

### Node.js version

20.10.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
That repository is private

**Comment by adonisv79** [comment]
k fine, I made it public. but it is easy to replicate honestly. I already noted it in the replication steps ;)

**Comment by jmcdo29** [comment]
[We have explicit docs about REQUEST scoped strategies](https://docs.nestjs.com/recipes/passport#request-scoped-strategies)

**Comment by adonisv79** [comment]
ok, thanks.
