### ISSUE TITLE
[discussion]: handleRequest to rely on Passport's errors

### ISSUE THREAD

**Issue by oleksiifinkratt** [nestjs/passport#1695]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I use auth guard is used with local strategy (following the official nestjs docs). It throws an unauthorised exception when the request body doesn't have the required username and password fields. 

I debugged the request. There is a function `handleRequest` in **auth.guard.ts**. It throws a new UnauthorizedException because it receives an empty `err` and `user`'s value is `false` there:
```
    handleRequest(err, user, info, context, status): TUser {
      if (err || !user) {
        throw err || new UnauthorizedException();
      }
      return user;
    }
```

At the same time the value of `context` is `Missing credentials` and `status` is `400`, but they are never used.

### Describe the solution you'd like

The package and its function `handleRequest()` rely on arguments `context` and `status` before checking the value of the argument `user`. Throw an HTTP exception according to the received `status` code and use the message from `context` (if not empty).

### What is the motivation / use case for changing the behavior?

Currently, the library ignores any authentication errors issued and collected by the Passport's library and its local strategy. I think it might be the same with other strategies.

When a request to the login endpoint doesn't have required fields such as username and password, it should get a response with the Bad Request status code, but it receives the Unauthorised status code.

I couldn't find a way how to get those errors generated by Passport and its strategies and throw a proper HTTP exception based on their status code.

**Comment by kamilmysliwiec** [comment]
> I couldn't find a way how to get those errors generated by Passport and its strategies and throw a proper HTTP exception based on their status code.

https://docs.nestjs.com/recipes/passport#extending-guards
