### ISSUE TITLE
Something wrong with nestjs/passport version

### ISSUE THREAD

**Issue by GregoryCaldeira** [nestjs/passport#1702]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hello,

I'm doing a nest app for a project I'm currently working and making the implementation of the passport I notice, importing `PassportStrategy` I got and error. Basically says `Module '"@nestjs/passport"' has no exported member 'PassportStrategy'`.

Going to the `package.json` I noticed this ` "@nestjs/passport": "github:nestjs/passport",`, so I change to `10.0.3` and after everything starts working.

### Minimum reproduction code

nothing

### Steps to reproduce

1 - `pnpm add @nestjs/passport`
2- Checking the `package.json`

### Expected behavior

When installed get the correct version `10.0.3`

### Package version

github:nestjs/passport

### Passport version

0.7.0

### NestJS version

10.0.0

### Node.js version

20.11.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
You shouldn't install it with the `github:` prefix because this repository is not prepared for such usage.
Not sure why you're doing that
