### ISSUE TITLE
Call resolve on error

### ISSUE THREAD

**Issue by apiel** [nestjs/passport#18]
https://github.com/nestjs/passport/blob/e9d1766dea6c1175b7010ca46b744a25b92b14f2/lib/auth.guard.ts#L86

            const createPassportContext = (request, response) => (type, options, callback) => new Promise((resolve, reject) => passport.authenticate(type, options, (err, user, info) => {
                try {
                    request.authInfo = info;
                    return resolve(callback(err, user, info));
                }
                catch (err) {
                    reject(err);
                }
            })(request, response, resolve));

https://github.com/jaredhanson/passport/blob/2327a36e7c005ccc7134ad157b2f258b57aa0912/lib/middleware/authenticate.js#L186

Here authenticate call "next" to trigger an error, but we provide "resolve" as "next" parameter. Shouldn't error call reject?

At least for me it's an issue. I follow the tutorial https://docs.nestjs.com/techniques/authentication and I don't get the 401 Unauthorized.

**Comment by apiel** [comment]
Maybe something like this:

```
const createPassportContext = (request, response) => (type, options, callback) => new Promise((resolve, reject) => {
    const next = (value) => {
        console.log('here we go', value);
        return value instanceof Error ? reject(value) : resolve(value);
    }
    return passport.authenticate(type, options, (err, user, info) => {
        try {
            request.authInfo = info;
            return resolve(callback(err, user, info));
        }
        catch (err) {
            reject(err);
        }
    })(request, response, next)
});
```
When I do this I get a 500 error, that make much more sense...

**Comment by DeX3** [comment]
I think the problem is that when you put an unknown strategy into AuthGuard (e.g. `@UseGuards(AuthGuard('whatever'))`) it won't complain.

**Comment by kamilmysliwiec** [comment]
I just pulled your repo and everything works well. I'm getting 401 when the token is not passed through the network, same as expected.

**Comment by apiel** [comment]
Yes because in the mid-time, I have been working on it... As @DeX3 described, change @UseGuards(AuthGuard('bearer'))) to @UseGuards(AuthGuard('whatever'))) you will then get no error and have access to the entry point.

Also, can you explain me why you are resolving error? Shouldn't error be rejected in a promise?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise#Parameters

> executor
> A function that is passed with the arguments resolve and reject. The executor function is executed immediately by the Promise implementation, passing resolve and reject functions (the executor is called before the Promise constructor even returns the created object). The resolve and reject functions, when called, resolve or reject the promise, respectively. The executor normally initiates some asynchronous work, and then, once that completes, either calls the resolve function to resolve the promise or **else rejects it if an error occurred. If an error is thrown in the executor function, the promise is rejected.** The return value of the executor is ignored.

**Comment by kamilmysliwiec** [comment]
> change @UseGuards(AuthGuard('bearer'))) to @UseGuards(AuthGuard('whatever'))) you will then get no error and have access to the entry point

The responsibility for checking whether a strategy exists belongs to passport library (that's why we cannot detect it earlier).

> Also, can you explain me why you are resolving error? Shouldn't error be rejected in a promise?

Because the resolved value is eventually passed to the `handleRequest` method anyway. See: https://github.com/nestjs/passport/blob/e9d1766dea6c1175b7010ca46b744a25b92b14f2/lib/auth.guard.ts#L62

**Comment by kamilmysliwiec** [comment]
You're absolutely right! Thank you for pointing me at this issue :) Fixed in 5.0.2

**Comment by cojack** [comment]
Close it ;)

**Comment by kfrajtak** [comment]
Hi. Was this really fixed? I have followed the guide and got the same error, I am using Nest 5.8.0.
