### ISSUE TITLE
PassportModule is not exposed in currently published passport library

### ISSUE THREAD

**Issue by chaostheory** [nestjs/passport#19]
## I'm submitting a...

<pre><code>
[x] Regression 
[] Bug report
[] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
I'm unable to replicate documented nestjs authentication example code because the PassportModule does not exist.

## Expected behavior
Example code should work as expected with the PassportModule exposed.

## Minimal reproduction of the problem with instructions
Unable to import PassportModule from @nestjs/passport

## What is the motivation / use case for changing the behavior?
I need to implement jwt based authentication

## Environment

<pre><code>
Nest version: 5.0.0
Nest Passport version: 1.1.0
 
For Tooling issues:
- Node version: 10.6.0
- Platform:  Windows

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Update your package to the latest version
