### ISSUE TITLE
Use nest.js passport with other passports

### ISSUE THREAD

**Issue by dmitriev02** [nestjs/passport#25]
How I can use nest.js with passport-steam authentication? Where I should put passport.use, auth routes, etc.? Is there any examples of how to use nest.js with other sites authentication (except Auth0)

**Comment by marvinrabe** [comment]
In the documentation you will find a detailed example on how to use the JWT passport strategy. You can adopt this to implement a Steam authentication with the `passport-steam` strategy.

See: https://docs.nestjs.com/techniques/authentication

**Comment by Luscazi** [comment]
**Use my example:** https://github.com/Luscazi/nest-passport-steam
