### ISSUE TITLE
Failure Redirect

### ISSUE THREAD

**Issue by sertsedat** [nestjs/passport#299]
How can I set failureRedirect option? I haven’t seen anything in documentation and it’s a crucial one.

**Comment by jmcdo29** [comment]
Please use our [Discord](https://discord.gg/nestjs) for support questions. We are using GitHub to track bug reports and feature requests.

**Comment by Expensiveee** [comment]
> How can I set failureRedirect option? I haven’t seen anything in documentation and it’s a crucial one.

Have you found something?

**Comment by sertsedat** [comment]
> > How can I set failureRedirect option? I haven’t seen anything in documentation and it’s a crucial one.
> 
> Have you found something?

Hey! It's been a while so I don't really remember. I think I solved it by an [ExceptionFilter](https://docs.nestjs.com/exception-filters) (?) and redirect from there but I am not sure and I cannot check the code since I don't have access to it anymore.
