### ISSUE TITLE
req.user is undefined after refresh.

### ISSUE THREAD

**Issue by yantrab** [nestjs/passport#32]
I can not make passport local work.
the login work , and return the user, but getUserAuthenticated retrun undefined.
[the project](https://github.com/yantrab/nest-angular/blob/master/server/src/auth/auth.controller.ts).

```
    @Post('login')
    @UseGuards(AuthGuard('local'))
    @HttpCode(HttpStatus.OK)
    async login(@Body() user: LoginRequest, @Req() req): Promise<User> {
// this is work fine.
        return req.user;
    }

    @Get('getUserAuthenticated')
    async getUserAuthenticated(@Req() req) {
// here req.user is undefined
        return {user:req.user};
    }
```

**Comment by kamilmysliwiec** [comment]
Please, use [StackOverflow](https://stackoverflow.com/questions/tagged/nestjs) for such questions.
