### ISSUE TITLE
UnauthorizedException handled internally

### ISSUE THREAD

**Issue by weeco** [nestjs/passport#4]
Following the NestJS JWT auth tutorial from the documentation I noticed that the UnauthorizedException is handled "internally". Instead of printing 

You'll get `{"statusCode":500,"message":"Internal server error"}` along with this log message `[Nest] #14156   14:59:46 - error:  [root] { statusCode: 401, error: 'Unauthorized' }`

It should print that error as JSON response along with the right http response code right?

**Comment by kamilmysliwiec** [comment]
Fixed in `v1.0.9`. Thanks for reporting

**Comment by kamilmysliwiec** [comment]
Also, make sure to get rid of internal `@nestjs/common` package installed by `@nestjs/passport` (full path: `node_modules/@nestjs/passport/node_modules/@nestjs/common`)

**Comment by demisx** [comment]
I was getting 500 Internal Error" response and seeing this in the log, until I've deleted `node_modules/@nestjs/passport/node_modules/@nestjs/common` package. I think I've accidentally ran `npm i` in `node_modules/@nestjs/passport/` directory instead of my project root. Thank you @kamilmysliwiec for your last comment. This saved me hours.

```
{
 "statusCode": 401,
 "error": "Unauthorized"
}
Error: [object Object]
   at MixinAuthGuard.handleRequest (/usr/src/dl/node_modules/@nestjs/passport/dist/auth.guard.js:63:30)
   at /usr/src/dl/node_modules/@nestjs/passport/dist/auth.guard.js:47:120
   at /usr/src/dl/node_modules/@nestjs/passport/dist/auth.guard.js:78:24
   ...
```

**Comment by furkangok** [comment]
Hello, i am using version 6.1.0, with an invalid JWT i get internal server error (500) with error message: 
{
    "message": "HttpException occured.",
    "exception": {
        "response": {
            "statusCode": 401,
            "error": "Unauthorized"
        },
        "status": 401,
        "message": {
            "statusCode": 401,
            "error": "Unauthorized"
        }
    }
}

But i want is to get 401 instead of 500. Could you please help me? TY.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
