### ISSUE TITLE
Support `fastify-passport` port

### ISSUE THREAD

**Issue by RobertLowe** [nestjs/passport#401]
Fastify has a newly ported passport implementation, it's alpha and has minor compatibility notes. Opening for discussion.

---

[X] Feature request

#### Current behavior
There is no passport support when using fastify.

#### Expected behavior
Add support for the new alpha `fastify-passport` https://github.com/fastify/fastify-passport

---

Thanks

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/passport/issues/397
