### ISSUE TITLE
Validate function and passport verify has different parameters

### ISSUE THREAD

**Issue by cerireyhan** [nestjs/passport#476]
I'm using passport-oauth2 strategy. I am able to use the default verify callback of the strategy, however, when I use the 'validate' function the 'results' param is empty. I'd appreciate any help/recommendation on the issue. 

The working code using verify function (results has userid & expires_in).
```
@Injectable()
export class WithingsStrategy extends PassportStrategy(Strategy, 'withings') {
    private readonly logger = new Logger(WithingsStrategy.name);

    constructor(private readonly configurationService: ConfigurationService) {
        super(
            {
                authorizationURL: configurationService.getAuthorizationUrl(),
                tokenURL: configurationService.getTokenUrl(),
                clientID: configurationService.getClientId(),
                clientSecret: configurationService.getClientSecret(),
                scope: ['user.info', 'user.metrics', 'user.activity'],
                scopeSeparator: ',',
                state: true,
            },
            (accessToken: string, refreshToken: string, results: any, profile: any, verify: VerifyCallback) =>
                verify(null, {
                    accessToken,
                    refreshToken,
                    expires: new Date(Date.now() + results.expires_in * 1000),
                    withingsId: results.userid,
                }),
        );
```

Validate function below doesn't work. results and profile are empty objects.
```
validate(accessToken: string, refreshToken: string, results: any, profile: any, verify: VerifyCallback) {
        return {
            accessToken,
            refreshToken,
            expires: new Date(Date.now() + results.expires_in * 1000),
            withingsId: results.userid,
        };
    }
```

I think this issue might be related to the tickets https://github.com/nestjs/passport/issues/434 and https://github.com/nestjs/passport/issues/446. However, I cannot find any information on the NestJS documentation regarding whether to include verify callback in validate or what is the recommended way.

**Comment by kamilmysliwiec** [comment]
> Validate function below doesn't work. results and profile are empty objects.

Remove the `verify` argument from the `validate` method as it's automatically provided.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by cerireyhan** [comment]
@kamilmysliwiec Validate parameter "results" is empty when verify is removed and validate is used only.

Thank you for replying so fast, also wrote the question to Discord channel but not sure if there is a bug with validate or the way it's used. (with done callback)

**Comment by cerireyhan** [comment]
@kamilmysliwiec I also tried using `validate` method without `verify` argument but `results` is still an empty object.

Sorry for bothering but Discord channel was not helpful on the issue and I wonder if the problem is on my side or in the lib.
