### ISSUE TITLE
Throwing errors and status codes in strategies are ignored by nestjs

### ISSUE THREAD

**Issue by smasala** [nestjs/passport#484]
Because of the following in passportjs 

```
return callback(null, false, failures[0].challenge, failures[0].status);
```
https://github.com/jaredhanson/passport/blob/1fd591d5cdcf6516d9eb446216843223c0e020c4/lib/middleware/authenticate.js#L107

Error messages and status codes are ignored at:
https://github.com/nestjs/passport/blob/ca21580a34e490c2aca519f737d3c6a56fde7984/lib/auth.guard.ts#L76-L78

This is because `err` is `null` and the values returned on failure by passportjs -> `this.fail('my error message', 123)` are passed as `info` and `status` at this point arguments.

Would be great is something like the following happened:

```typescript
if (err || !user) {
   throw err || (info && status ? new HttpException(info, status) : new UnauthorizedException());
}
```

**Comment by kamilmysliwiec** [comment]
https://docs.nestjs.com/security/authentication#extending-guards

**Comment by smasala** [comment]
@kamilmysliwiec thanks for the link. Seems a bit odd to extend this plugin (create a wrapper guard) just to catch and return errors from passport correctly? I would have expected this plugin to do it properly as it already sits on top of passport.
