### ISSUE TITLE
Get correct parameters in Strategy

### ISSUE THREAD

**Issue by luqezman** [nestjs/passport#490]
## I'm submitting a...
[x] Bug report

## Current behavior
Im trying to use [passport-faceit](https://www.npmjs.com/package/passport-faceit) to authenticate my api but my "Strategy.validate" method in nestjs only returns 4 parameters instead of 5 like passport-faceit description.

I tried without nestjs/passport inside nestjs project and everything works like a charm.

I want to know what is happening or I want to know if I need to do something more?

Thanks

## Expected behavior
I want to get 5 parameters like in passport-faceit example:

```
passport.use(new faceitStrategy({
    clientID: FACEIT_CLIENT_ID,
    clientSecret: FACEIT_CLIENT_SECRET
  },
  # Like this
  function(accessToken, refreshToken, params, profile, done) {
    const userData = jwt.decode(params.id_token);
 
    done(null, {
      faceitId: userData.guid,
      faceitAvatar: userData.picture,
      faceitEmail: userData.email,
      faceitNickname: userData.nickname
    });
  }
));
```

## Environment

Nest version: 7.2.0
 
For Tooling issues:
- Node version: v12.16.3
- Platform:  Windows

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several times in the past). + potential solution https://github.com/nestjs/passport/issues/446#issuecomment-733607803
