### ISSUE TITLE
TSError: Call target does not contain any signatures

### ISSUE THREAD

**Issue by cdiaz** [nestjs/passport#6]
## Current Behavior

`TSError: ⨯ Unable to compile TypeScript
src/auth/jwt.strategy.ts (10,5): Call target does not contain any signatures. (2346)
`

[src/auth/jwt.strategy.ts](https://github.com/nestjs/nest/blob/master/sample/19-auth/src/auth/jwt.strategy.ts#L10) super() constructor extending from `PassportStrategy` does not contain any signatures:

```js
export class JwtStrategy extends PassportStrategy(Strategy) {
  constructor(private readonly authService: AuthService) {
    super({
      jwtFromRequest: ExtractJwt.fromAuthHeaderAsBearerToken(),
      secretOrKey: 'secretKey',
    });
  }
```

## Environment
<pre><code>
Nest version: 5.0.0-rc.3
@nestjs/passport: v1.0.9
TypeScript: 2.8.3

 
For Tooling issues:
- Node version: 10.0.0
- Platform:  Linux
</code></pre>

**Comment by kamilmysliwiec** [comment]
Fixed in `v1.0.10`. Lemme know if you face any issues

**Comment by cdiaz** [comment]
This issue has been fixed,  Thanks

**Comment by KedzierskiDawid** [comment]
Hi guys, I have exactly the same issue when I'm trying to debug example 19-auth from official samples even with @nestjs/passport in 1.0.10 version. Could you look at this, please?

## Environment
```
Nest version: 5.0.1
@nestjs/passport: 1.0.10
TypeScript: 2.8.1

Node version: 9.8.0
Platform: Windows
```

**Comment by kamilmysliwiec** [comment]
@KedzierskiDawid let's try `1.0.11` and lemme know if you face any issue
