### ISSUE TITLE
Does 'nestjs/passport' support fastify?

### ISSUE THREAD

**Issue by arekbal** [nestjs/passport#60]
<pre><code>
[x] Feature request
[x] Documentation issue or request
</code></pre>

From my understanding:
**'passport' is highly reliant on 'express'. Therefore 'nestjs/passport' does not support 'fastify' or other httpadapters one might use.**

I would just like it to be clarified to me, and if true, to be 'noted' in docs.

**Comment by kamilmysliwiec** [comment]
Passport library doesn't support fastify https://github.com/fastify/fastify/issues/147

**Comment by mubaidr** [comment]
Is this still valid? If I am using `@nestjs/platform-fastify` that means I cannot use `@nestjs/passport`? 

Trying to integrate these together, `jwt` strategy works fin, but:

- `local` strategy does not seems to work
- `@Req` or `@Request` is always undefined for resolvers.

**Comment by kamilmysliwiec** [comment]
@mubaidr correct.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
