### ISSUE TITLE
Passwordless Auth

### ISSUE THREAD

**Issue by fred76** [nestjs/passport#683]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

How implement Passwordless Auth.
Without external provider
I found this passport strategy but I cannot integrate in Nestjs in any way.

https://github.com/mxstbr/passport-magic-login

### Describe the solution you'd like

passwordless strategy

### What is the motivation / use case for changing the behavior?

passwordless

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
