### ISSUE TITLE
Allow to log details about the cause of a 401 error

### ISSUE THREAD

**Issue by Delapouite** [nestjs/passport#699]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Hello

I developed a Nest.js application where the HTTP authentication is using the Passport Strategy with JWT.
Everything looked fine, but the consumers of this REST API were getting `401` error again and again for a yet unknown reason.
Unfortunately, the server logs remained silent with no clue about what could be the problem.

In the end I did find what was going on: it was a mistake about a wrong audience value in the JWT.

In order to reach this conclusion, I had to run the server in dev mode and attach a debugger to inspect the call stacks: 
![image](https://user-images.githubusercontent.com/39315/138135458-b71b9f55-ba65-4944-ba02-0622e251c56b.png)

The explicit message about the audience issue, is available on the `info` object provided to the `handleRequest` method, but unfortunately it is not used and there does not seem an easy way to retrieve it.

### Describe the solution you'd like

Could adding an optional `logger.error()` statement, outputting the content of the `info` variable (if not empty) be possible? Or is there any better solution to surface this underlying issue?

Thanks!

### What is the motivation / use case for changing the behavior?

To improve developer experience in a debug scenario, to avoid being blind about the root cause of an auth issue with Passport + JWT.

**Comment by kamilmysliwiec** [comment]
> We could possibly add info to the UnauthorizedException if it's not null. Do something like throw err || new UnauthorizedException(info ?? undefined). I've definitely seen a lot of issues with JWT integration based on things like audience or expired tokens that just throws a 401 without more info. This would be helpful for sure

This would be a breaking change.

> Could adding an optional logger.error() statement, outputting the content of the info variable (if not empty) be possible? 

We could add `logger.verbose()` call here I guess.

> provided to the handleRequest method, but unfortunately it is not used and there does not seem an easy way to retrieve it.

There's a very straightforward way to override the default behavior, check out this section https://docs.nestjs.com/security/authentication#extending-guards
