### ISSUE TITLE
Passport's logIn() function is not called

### ISSUE THREAD

**Issue by blissi** [nestjs/passport#7]
Hallo,
when using the guard to protect the login-route, the user is correctly set at the request-object when the user passes the right credentials (I am using the LocalStrategy). So I though, everything would be alright...
but the user is not persisted to the session.

By debugging I found out that the AuthGuard doesn't call Passport's logIn()-function and therefore the user is only set to the request, but not persisted to the session. I believe this is quite an unexpected behavior for most users because it is different to the default way that Passport works.

In my opinion this should either be fixed or at least documented.

**Comment by artonio** [comment]
Yes I ran into the same issue, the documentation is quite young but I did manage to get it working, and here is a tutorial on it: [NestJS Basic Auth and Sessions Tutorial](http://blog.exceptionfound.com/index.php/2018/06/07/nestjs-basic-auth-and-sessions/)

**Comment by Kapnobatai3434** [comment]
Hey guys, will this fix be merged into the master branch?

**Comment by kamilmysliwiec** [comment]
See **Inheritance** section https://docs.nestjs.com/techniques/authentication

**Comment by Offlein** [comment]
I'm confused by the Inheritance section you refer to, @kamilmysliwiec.

In that section, you have a code comment that reads:
```
// Add your custom authentication logic here
// for example, call super.logIn(request) to establish a session.
```

But request is not defined in that context. I assume I am meant to get it instead like `super.logIn(context.switchToHttp().getRequest());`? 

As well, there's a sample app for this section (https://github.com/nestjs/nest/tree/master/sample/19-auth/src) which has a `jwt-auth.guard.ts` file in, but that file isn't even seemingly called from anywhere.

Assuming that the `super.logIn` method actually works (and it would be great to understand how and why this is happening), I didn't understand for a while how to implement my custom `AuthGuard` child class. 

Finally, I imported it as a provider in the .module.ts file, and then, in my controller, replaced the `@UseGuards(AuthGuard('google'))` line I had (..using Google, obviously!) with `@UseGuards(GoogleAuthGuard)`, and I think I might be at least moving forward.

...Although I'm getting issues in my Google strategy now, so we'll see what's up there. :)
