### ISSUE TITLE
Can a new release be pushed?

### ISSUE THREAD

**Issue by kertof** [nestjs/passport#781]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

The last release was in August 2021, since then, the Passport lib has been bumped to 0.5.0, but the released version of @nestjs/passport requires passport@0.4.0 as a peerDeps.

The version requirement has been updated in the package.json file, but the change has not been released.

### Describe the solution you'd like

Publish a new release of the library,

### What is the motivation / use case for changing the behavior?

Avoid issues when NPM installing, which currently requires using the --legacy-peer-deps flag to install.

**Comment by jmcdo29** [comment]
What's `0.5.0` bring to the passport library? Looks like it changed where the `request.login()` method (and similar) gets set from so that `initialize()` needs to be called? Anything else that I'm missing

**Comment by kamilmysliwiec** [comment]
Just released
