### ISSUE TITLE
Cannot read properties of undefined (reading 'property')

### ISSUE THREAD

**Issue by CatsMiaow** [nestjs/passport#826]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

In my project, `@nestjs/passport` was used by extending `AuthGuard` from v8.1.0, but after updating to `v8.2.0`, an error occurred.
An error is occurring when running `super.logIn(request)`.
https://github.com/nestjs/passport/blob/954ed801c5f371abbcbffd2b3caa8d2b9a20d57d/lib/auth.guard.ts#L73-L76

I updated the module based on the [nest sample](https://github.com/nestjs/nest/tree/master/sample/19-auth-jwt) and made the Minimum reproduction code.

### Minimum reproduction code

https://github.com/CatsMiaow/19-auth-jwt

### Steps to reproduce

![image](https://user-images.githubusercontent.com/1300172/154229230-1dd11ce6-5469-4119-b608-8790d7a42ba9.png)

### Expected behavior

There should be no errors.

### Package version

8.2.0

### Passport version

0.5.2

### NestJS version

8.3.0

### Node.js version

16.13.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

~~Perhaps it has something to do with this [PR](https://github.com/nestjs/passport/pull/824).~~

**Comment by kamilmysliwiec** [comment]
Fixed in 8.2.1
