### ISSUE TITLE
Not able to pass info object from Custom Passport Stategy

### ISSUE THREAD

**Issue by vimalraj-a** [nestjs/passport#89]
Since validate function is being considered as promise don't send callback function of passport. Because callback function is called from after validate function completed Ref: `passport.strategy.ts`.

Moreover, I don't understand how to pass `info` (3rd parameter of callback). Since its being used for `authInfo` field of request object in `auth.guard.ts` file. 

https://github.com/nestjs/passport/blob/8acdc04e6210aefab7a6e2ac4009e788bc8de5b8/lib/passport/passport.strategy.ts#L14-L24

https://github.com/nestjs/passport/blob/8acdc04e6210aefab7a6e2ac4009e788bc8de5b8/lib/auth.guard.ts#L82-L89

**Comment by csidell-earny** [comment]
When you return from the validate function return [ <user>, <info> ].
