### ISSUE TITLE
PassportStrategy interface does not contain validate()

### ISSUE THREAD

**Issue by MickL** [nestjs/passport#929]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When following the documentation and extending `PassportStrategy` the interface does not contain a `validate()` function and is therefor kinda useless.

```
import { Injectable } from '@nestjs/common';
import { PassportStrategy } from '@nestjs/passport';
import { Strategy } from 'passport-local';

@Injectable()
export class JwtStrategy extends PassportStrategy(Strategy) {
...
}
```

The interface `passport.strategy.d.ts` looks like this:

```
import { Type } from '../interfaces';
export declare function PassportStrategy<T extends Type<any> = any>(Strategy: T, name?: string | undefined): {
    new (...args: any[]): InstanceType<T>;
};
```

I guess this is a bug because in the [source file](https://github.com/nestjs/passport/blob/9d7b4fa69ac889c5f0fb7f69ae3c7e467c41b4a1/lib/passport/passport.strategy.ts#L11) there is an abstract method.

The behavior is the same in latest 7.x and 8.x

### Minimum reproduction code

https://github.com/nestjs/nest/tree/master/sample/19-auth-jwt

### Expected behavior

The class PassportStrategy should contain an abstract `validate()` function

### Package version

8.x

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

In general it is weird that there is no functions what so ever. For example there are functions available like `this.success()`, `this.pass()`, `this.error()` that are also not part of the interface.

**Comment by AarNtyon** [comment]
a year has passed

**Comment by jmcdo29** [comment]
> a year has passed

And no one has made a PR for it. Would you like to @AarNtyon?

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/passport/pull/1641
