### ISSUE TITLE
The defaultStrategies cannot be set during runtime in the AuthGuard

### ISSUE THREAD

**Issue by eesdil** [nestjs/passport#946]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The `defaultStrategies` are ignored when they are passed from the `getAuthenticateOptions` method.

Although the `getAuthenticateOptions` method allows the defaultStrategies to be set, see signiture: 
`getAuthenticateOptions(context): IAuthModuleOptions | undefined;`
```
export interface IAuthModuleOptions<T = any> {
  defaultStrategy?: string | string[];
  session?: boolean;
  property?: string;
  [key: string]: any;
}
```

### Minimum reproduction code

https://github.com/nestjs/passport/blob/master/lib/auth.guard.ts

### Steps to reproduce

1. set a defaultStrategy in the getAuthenticateOptions method
2. use the guard on an endpoint
3. the strategy is not used, even though it is set in the options

In the code (AuthGuard) the authenticate options are extending the options (see line 49) but in line 57 this options is not used.

### Expected behavior

The `defaultStrategies` can be set/used during run time via the `getAuthenticateOptions` method.

### Package version

8.2.2

### Passport version

0.6.0

### NestJS version

8.4.7

### Node.js version

16.15.1

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

Code it maybe extended like this:
```
    async canActivate(context: ExecutionContext): Promise<boolean> {
      const authenticateOptions = await this.getAuthenticateOptions(context);
      const options = {
        ...defaultOptions,
        ...this.options,
        ...authenticateOptions
      };
      const [request, response] = [
        this.getRequest(context),
        this.getResponse(context)
      ];
      const passportFn = createPassportContext(request, response);
      const user = await passportFn(
        authenticateOptions.defaultStrategy || type || this.options.defaultStrategy,
        options,
        (err, user, info, status) =>
          this.handleRequest(err, user, info, context, status)
      );
      request[options.property || defaultOptions.property] = user;
      return true;
    }
```

Although the error message would be misleading now able to have an empty type as default.

The other option is to disable adding the defaultStrategy with using different signature: Omit<IAuthModuleOptions, 'defaultStrategy'>

thanks

**Comment by kamilmysliwiec** [comment]
This is the expected behavior.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
